### ISSUE TITLE
erro no make validate

### ISSUE THREAD

**Issue by kesiabomfa** [transparencia-mg/remuneracao#60]
Estou com um erro no make validate, ao rodar esses passos: https://github.com/transparencia-mg/remuneracao/blob/master/USAGE.md

![MicrosoftTeams-image](https://github.com/transparencia-mg/remuneracao/assets/52920939/1d7808e3-f67b-4bdf-a87f-76d2eae7a6cb)

**Comment by AntonioMarcel** [comment]
Erro solucionado. Solução: comentar no arquivo makefile os comandos livemark:

![image](https://github.com/transparencia-mg/remuneracao/assets/66658941/e0d87bae-7ab2-44ed-94b9-0907d8ded7a6)

- A biblioteca [livemark](https://github.com/frictionlessdata/livemark) já está sem novos commits desde junho de 2023. 
- Além disso, os arquivos html que são gerados ao rodar o comando não são necessários para a alimentação dos dados de remuneração.
